### ISSUE TITLE
Python syntax differences

### ISSUE THREAD

**Issue by vkaracic** [thenikso/github-plus-theme#10]
The Python syntax highlight in this theme:
![Screenshot from 2019-04-29 15-33-10](https://user-images.githubusercontent.com/2808092/56899645-3f3a4c00-6a94-11e9-847e-9edd090e3217.png)

differs greatly from the syntax highlight on Github:
![Screenshot from 2019-04-29 15-33-05](https://user-images.githubusercontent.com/2808092/56899663-4a8d7780-6a94-11e9-86c2-ddb6c103a147.png)

Am I doing something wrong or is Python not supported?

**Comment by Arcitec** [comment]
The situation is better these days but yeah this is still an issue.

**Comment by Arcitec** [comment]
@vkaracic Well, look at this repo history. Sure, the github-plus-theme colors are nice, but it only supports a few languages, and there are barely any updates for years. That is no fault of nikso; I know everything about not having energy to maintain projects. We all reach that point when something works well enough for us and we have no passion to make it into something bigger.

But that is where Dracula (Official) comes in. They have, without a doubt, the best syntax highlighting of all VS Code themes, with support for ALL programming languages. Sadly they are a dark theme. But a smart guy forked the project and wrote a script which uses eye-vision/contrast algorithms to automatically generate a light version of the theme. With his fork, you will have all of the PERFECT, VERY ADVANCED syntax highlighting of Dracula, and a light background to enjoy.

Here are the themes:

- Dark (original): https://marketplace.visualstudio.com/items?itemName=dracula-theme.theme-dracula
- Light (fork): https://marketplace.visualstudio.com/items?itemName=ashrafhadden.dracula-dot-min

And if someone truly wants the specific github colors for their light theme instead, then you should simply fork Dracula yourself and edit its `.yaml` file which defines all colors, and run the build script to generate a perfect light theme. Simply put, Dracula is the best foundation for ANY syntax highlighting theme ever. Even better than VSCode's built in themes. So that is why I am now giving up on incomplete 3rd party light themes, and going with the light-colored fork of Dracula instead.
