### ISSUE TITLE
Request - github-plus-theme-dark

### ISSUE THREAD

**Issue by jasgagne** [thenikso/github-plus-theme#18]
I love your theme so much! I love the colors you chose! Do you have any plans to create a dark version of this theme following the same syntax highlighting etc?

**Comment by thenikso** [comment]
I have no plans atm as I have been of the "dark text on clear background is the best!" school since I've created this theme 😄  

If you checkout the [forks](https://github.com/thenikso/github-plus-theme/network/members) there are some (ie: [this](https://github.com/joaomoreno/github-sharp-theme)) that have a dark variant.

I might one day do my own take but I make no promises
